apiVersion: v1
kind: Service
metadata:
  labels:
    app: boilerplate-webapp
  name: boilerplate-webapp
spec:
  ports:
    - name: '3000'
      port: 3000
      targetPort: 3000
  selector:
    app: boilerplate-webapp
