apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boilerplate-webapp
  name: boilerplate-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-webapp
  template:
    metadata:
      labels:
        app: boilerplate-webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: eoscostarica506/boilerplate-webapp:qa
          imagePullPolicy: 'Always'
          name: boilerplate-webapp
          envFrom:
            - configMapRef:
                name: boilerplate-webapp-config
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /etc/nginx/ssl-certs
              name: secret-volume
            - mountPath: /etc/nginx/conf.d
              name: configmap-volume
      restartPolicy: Always
      volumes:
        - name: secret-volume
          secret:
            secretName: boilerplate.io.keys
        - name: configmap-volume
          configMap:
            name: boilerplate.io.conf
