apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boilerplate-hapi
  name: boilerplate-hapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-hapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: boilerplate-hapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: eoscostarica506/boilerplate-hapi
          imagePullPolicy: 'Always'
          name: 'boilerplate-hapi'
          envFrom:
            - configMapRef:
                name: boilerplate-hapi-config
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /usr/app
              name: hapi
              subPathExpr: $(CODE_DIRECTORY)
      restartPolicy: Always
      volumes:
        - name: hapi
          nfs:
            server: nfs-server-new
            path: /home/ubuntu/
