apiVersion: v1
kind: Service
metadata:
  labels:
    app: boilerplate-hasura
  name: boilerplate-hasura
spec:
  ports:
    - name: hasura
      port: 8080
      targetPort: 8080
  selector:
    app: boilerplate-hasura
